# >>> wp-bootstrap: {{PROJECT_NAME}} >>>
# {{PROJECT_NAME}} {{TODAY_DATE}}
<VirtualHost *:80>
    ServerAdmin {{VHOST_EMAIL}}
    DocumentRoot {{DOCUMENT_ROOT}}
    ServerName {{LOCAL_DOMAIN}}
    <Directory {{DOCUMENT_ROOT}}>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog {{ERROR_LOG_PATH}}
    CustomLog {{ACCESS_LOG_PATH}} combined
</VirtualHost>
# <<< wp-bootstrap: {{PROJECT_NAME}} <<<
